// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// inference.cpp
cpp11::writable::doubles ort_run(SEXP session_ptr, cpp11::doubles input_array, cpp11::integers input_shape, std::string input_name, std::string output_name);
extern "C" SEXP _nativeORT_ort_run(SEXP session_ptr, SEXP input_array, SEXP input_shape, SEXP input_name, SEXP output_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_run(cpp11::as_cpp<cpp11::decay_t<SEXP>>(session_ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(input_array), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(input_shape), cpp11::as_cpp<cpp11::decay_t<std::string>>(input_name), cpp11::as_cpp<cpp11::decay_t<std::string>>(output_name)));
  END_CPP11
}
// nativeORT.cpp
std::string ort_version();
extern "C" SEXP _nativeORT_ort_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_version());
  END_CPP11
}
// ort_loader.cpp
bool ort_load_lib(std::string path);
extern "C" SEXP _nativeORT_ort_load_lib(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_load_lib(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// ort_loader.cpp
bool ort_is_loaded();
extern "C" SEXP _nativeORT_ort_is_loaded() {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_is_loaded());
  END_CPP11
}
// session.cpp
SEXP ort_create_env();
extern "C" SEXP _nativeORT_ort_create_env() {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_create_env());
  END_CPP11
}
// session.cpp
SEXP ort_create_session(SEXP env_ptr, std::string model_path, std::string provider, std::string cache_dir, int threads, int opt_level);
extern "C" SEXP _nativeORT_ort_create_session(SEXP env_ptr, SEXP model_path, SEXP provider, SEXP cache_dir, SEXP threads, SEXP opt_level) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_create_session(cpp11::as_cpp<cpp11::decay_t<SEXP>>(env_ptr), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_path), cpp11::as_cpp<cpp11::decay_t<std::string>>(provider), cpp11::as_cpp<cpp11::decay_t<std::string>>(cache_dir), cpp11::as_cpp<cpp11::decay_t<int>>(threads), cpp11::as_cpp<cpp11::decay_t<int>>(opt_level)));
  END_CPP11
}
// session.cpp
int ort_session_input_count(SEXP session_ptr);
extern "C" SEXP _nativeORT_ort_session_input_count(SEXP session_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_session_input_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(session_ptr)));
  END_CPP11
}
// session.cpp
int ort_session_output_count(SEXP session_ptr);
extern "C" SEXP _nativeORT_ort_session_output_count(SEXP session_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_session_output_count(cpp11::as_cpp<cpp11::decay_t<SEXP>>(session_ptr)));
  END_CPP11
}
// session.cpp
cpp11::writable::strings ort_session_input_names(SEXP session_ptr);
extern "C" SEXP _nativeORT_ort_session_input_names(SEXP session_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_session_input_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(session_ptr)));
  END_CPP11
}
// session.cpp
cpp11::writable::strings ort_session_output_names(SEXP session_ptr);
extern "C" SEXP _nativeORT_ort_session_output_names(SEXP session_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(ort_session_output_names(cpp11::as_cpp<cpp11::decay_t<SEXP>>(session_ptr)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_nativeORT_ort_create_env",           (DL_FUNC) &_nativeORT_ort_create_env,           0},
    {"_nativeORT_ort_create_session",       (DL_FUNC) &_nativeORT_ort_create_session,       6},
    {"_nativeORT_ort_is_loaded",            (DL_FUNC) &_nativeORT_ort_is_loaded,            0},
    {"_nativeORT_ort_load_lib",             (DL_FUNC) &_nativeORT_ort_load_lib,             1},
    {"_nativeORT_ort_run",                  (DL_FUNC) &_nativeORT_ort_run,                  5},
    {"_nativeORT_ort_session_input_count",  (DL_FUNC) &_nativeORT_ort_session_input_count,  1},
    {"_nativeORT_ort_session_input_names",  (DL_FUNC) &_nativeORT_ort_session_input_names,  1},
    {"_nativeORT_ort_session_output_count", (DL_FUNC) &_nativeORT_ort_session_output_count, 1},
    {"_nativeORT_ort_session_output_names", (DL_FUNC) &_nativeORT_ort_session_output_names, 1},
    {"_nativeORT_ort_version",              (DL_FUNC) &_nativeORT_ort_version,              0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_nativeORT(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
