# Generated by cpp11: do not edit by hand

ort_run_ <- function(session_ptr, inputs, input_shapes, input_names, input_types, output_names) {
  .Call(`_nativeORT_ort_run_`, session_ptr, inputs, input_shapes, input_names, input_types, output_names)
}

ort_version <- function() {
  .Call(`_nativeORT_ort_version`)
}

ort_load_lib <- function(path) {
  .Call(`_nativeORT_ort_load_lib`, path)
}

ort_is_loaded <- function() {
  .Call(`_nativeORT_ort_is_loaded`)
}

ort_create_env <- function() {
  .Call(`_nativeORT_ort_create_env`)
}

ort_create_session <- function(env_ptr, model_path, provider, cache_dir, threads, opt_level, external_data_files) {
  .Call(`_nativeORT_ort_create_session`, env_ptr, model_path, provider, cache_dir, threads, opt_level, external_data_files)
}

ort_session_input_count <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_count`, session_ptr)
}

ort_session_output_count <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_count`, session_ptr)
}

ort_session_input_names <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_names`, session_ptr)
}

ort_session_output_names <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_names`, session_ptr)
}

ort_session_input_shapes <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_shapes`, session_ptr)
}

ort_session_output_shapes <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_shapes`, session_ptr)
}

ort_session_input_types <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_types`, session_ptr)
}

ort_session_output_types <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_types`, session_ptr)
}
