# Generated by cpp11: do not edit by hand

ort_run <- function(session_ptr, input_array, input_shape, input_name, output_name) {
  .Call(`_nativeORT_ort_run`, session_ptr, input_array, input_shape, input_name, output_name)
}

ort_version <- function() {
  .Call(`_nativeORT_ort_version`)
}

ort_load_lib <- function(path) {
  .Call(`_nativeORT_ort_load_lib`, path)
}

ort_is_loaded <- function() {
  .Call(`_nativeORT_ort_is_loaded`)
}

ort_create_env <- function() {
  .Call(`_nativeORT_ort_create_env`)
}

ort_create_session <- function(env_ptr, model_path, provider, cache_dir, threads, opt_level) {
  .Call(`_nativeORT_ort_create_session`, env_ptr, model_path, provider, cache_dir, threads, opt_level)
}

ort_session_input_count <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_count`, session_ptr)
}

ort_session_output_count <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_count`, session_ptr)
}

ort_session_input_names <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_input_names`, session_ptr)
}

ort_session_output_names <- function(session_ptr) {
  .Call(`_nativeORT_ort_session_output_names`, session_ptr)
}
