# Generated by cpp11: do not edit by hand

onnx_run_ <- function(session_ptr, inputs, input_shapes, input_names, input_types, output_names) {
  .Call(`_onnxr_onnx_run_`, session_ptr, inputs, input_shapes, input_names, input_types, output_names)
}

onnx_load_lib <- function(path) {
  .Call(`_onnxr_onnx_load_lib`, path)
}

onnx_is_loaded <- function() {
  .Call(`_onnxr_onnx_is_loaded`)
}

onnx_unload_lib <- function() {
  invisible(.Call(`_onnxr_onnx_unload_lib`))
}

onnx_version <- function() {
  .Call(`_onnxr_onnx_version`)
}

onnx_create_env <- function() {
  .Call(`_onnxr_onnx_create_env`)
}

onnx_create_session <- function(env_ptr, model_path, provider, cache_dir, threads, opt_level) {
  .Call(`_onnxr_onnx_create_session`, env_ptr, model_path, provider, cache_dir, threads, opt_level)
}

onnx_session_input_count <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_input_count`, session_ptr)
}

onnx_session_output_count <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_output_count`, session_ptr)
}

onnx_session_input_names <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_input_names`, session_ptr)
}

onnx_session_output_names <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_output_names`, session_ptr)
}

onnx_session_input_shapes <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_input_shapes`, session_ptr)
}

onnx_session_output_shapes <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_output_shapes`, session_ptr)
}

onnx_session_input_types <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_input_types`, session_ptr)
}

onnx_session_input_optional <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_input_optional`, session_ptr)
}

onnx_session_output_types <- function(session_ptr) {
  .Call(`_onnxr_onnx_session_output_types`, session_ptr)
}
